FROM python:3.9

WORKDIR /app

ADD . /app

RUN python3 -m pip install --no-cache-dir --upgrade -r requirements.txt
RUN python3 -m pip install . --no-cache-dir

COPY ./{{lib_name}}/{{lib_name.lower()}}_server.py /app

CMD ["uvicorn", "{{lib_name.lower()}}_server:app", "--host", "0.0.0.0", "--port", "80"]